version: '3'
services:
  user-microservice:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./user-service:/app
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: 'MY_JWT_SECRET'
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
