export const moviesSeedData = [
  {
    id: 1,
    title: 'The Shawshank Redemption',
    director: 'Frank Darabont',
    actors: ['Tim Robbins', 'Morgan Freeman'],
    genre: ['Drama'],
    ratings: 9.3,
    ticket_price: 12.5,
  },
  {
    id: 2,
    title: 'The Godfather',
    director: 'Francis Ford Coppola',
    actors: ['Marlon Brando', 'Al Pacino', 'James Caan'],
    genre: ['Crime', 'Drama'],
    ratings: 9.2,
    ticket_price: 13.0,
  },
  {
    id: 3,
    title: 'The Dark Knight',
    director: 'Christopher Nolan',
    actors: ['Christian Bale', 'Heath Ledger', 'Gary Oldman'],
    genre: ['Action', 'Crime', 'Drama'],
    ratings: 9.0,
    ticket_price: 11.5,
  },
  {
    id: 4,
    title: 'Pulp Fiction',
    director: 'Quentin Tarantino',
    actors: ['John Travolta', 'Samuel L. Jackson', 'Uma Thurman'],
    genre: ['Crime', 'Drama'],
    ratings: 8.9,
    ticket_price: 11.0,
  },
  {
    id: 5,
    title: 'Inception',
    director: 'Christopher Nolan',
    actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    ratings: 8.8,
    ticket_price: 12.0,
  },
];
