apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-booking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-booking-app
  template:
    metadata:
      labels:
        app: ticket-booking-app
  spec:
    containers:
      - name: user-service
        image: bhadash1/ticket-booking-user-service:latest
        ports:
          - containerPort: 3001
        env:
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: 27017
            - name: MONGO_DB_NAME
              value: db
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: 6379
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: JWT_SECRET
              value: 'MY_JWT_SECRET'
      - name: booking-service
        image: bhadash1/ticket-booking-booking-service:latest
        ports:
          - containerPort: 3002
        env:
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: 27017
            - name: MONGO_DB_NAME
              value: db
            - name: RABBITMQ_HOST
              value: rabbitmq
      - name: booking-service
        image: bhadash1/ticket-booking-api-gateway:latest
        ports:
          - containerPort: 3000
        env:
            - name: USER_SVC_HOST
              value: user-service
            - name: BOOKING_SVC_HOST
              value: booking-service
      - name: mongodb
        image: mongo:latest
        ports:
          - containerPort: 27017
      - name: redis
        image: redis:latest
        ports:
          - containerPort: 6379
      - name: rabbitmq
        image: rabbitmq:3.10-management
        ports:
          - containerPort: 5672