apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-booking-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-booking-platform
  template:
    metadata:
      labels:
        app: movie-booking-platform
    spec:
      containers:
        - name: user-service
          image: ticket-booking-user-service:latest
          ports:
            - containerPort: 3001
        - name: booking-service
          image: ticket-booking-booking-service:latest
          ports:
            - containerPort: 3002
        - name: api-gateway
          image: ticket-booking-api-gateway:latest
          ports:
            - containerPort: 3000
            - targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
