apiVersion: v1
kind: Service
metadata:
  name: ticket-booking-app
spec:
  type: NodePort
  selector:
    app: ticket-booking-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
    - protocol: TCP
      port: 81
      targetPort: 3001
