name: Build and Push to Docker Hub(api-gateway)

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./user-service

      - name: Run tests
        run: npm run test
        working-directory: ./user-service

      - name: Build the application
        run: npm run build
        working-directory: ./user-service

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build push [api-gateway] Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/api-gateway:latest -f ./api-gateway/Dockerfile ./api-gateway
          docker push ${{ secrets.DOCKER_USER }}/api-gateway:latest
      
      - name: Build push [user-service] Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/user-service:latest -f ./user-service/Dockerfile ./user-service
          docker push ${{ secrets.DOCKER_USER }}/user-service:latest

      - name: Build push [booking-service] Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/booking-service:latest -f ./booking-service/Dockerfile ./booking-service
          docker push ${{ secrets.DOCKER_USER }}/booking-service:latest
