name: SonarCloud Scan
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies [booking-service]
        run: npm install
        working-directory: ./booking-service
      - name: Run tests [booking-service]
        run: npm run test:cov
        working-directory: ./booking-service

      - name: Install dependencies [user-service]
        run: npm install
        working-directory: ./user-service
      - name: Run tests [user-service]
        run: npm run test:cov
        working-directory: ./user-service
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}